apiVersion: v1
kind: Service
metadata:
  name: nodejs-mysql-service
  labels:
    app: crud-app
spec:
  ports:
    - port: 3306
  selector:
    app: crud-app
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: crud-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-mysql-deployment
  labels:
    app: crud-app
spec:
  selector:
    matchLabels:
      app: crud-app
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: crud-app
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: socka
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: local-volume
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: local-volume
        hostPath:
          path: /sqldump
