apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  labels:
    app: crud-app
spec:
  ports:
    - port: 80
  selector:
    app: crud-app
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: crud-app
spec:
  selector:
    matchLabels:
      app: crud-app
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: crud-app
        tier: frontend
    spec:
      containers:
      - image: juliuscanute/node-mysql-crud-app:latest
        name: crud-app
        env:
        - name: MYSQL_DB_HOST
          value: nodejs-mysql
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: crud-app
