apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  labels:
    app: crud-app
spec:
  ports:
    - port: 2000
  selector:
    app: crud-app
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-app-pv-claim
  labels:
    app: crud-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: crud-app
spec:
  selector:
    matchLabels:
      app: crud-app
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: crud-app
        tier: frontend
    spec:
      containers:
      - image: juliuscanute/node-mysql-crud-app:release-1.0.1
        name: crud-app
        env:
        - name: MYSQL_DB_HOST
          value: nodejs-mysql
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 2000
          name: crud-app
        volumeMounts:
          - name: nodejs-app-storage
            mountPath: /usr/share/website/public/assets/img
      volumes:
        - name: nodejs-app-storage
          persistentVolumeClaim:
            claimName: nodejs-app-pv-claim